[package]
name = "xtask"
version = "0.42.0"
edition = "2024"
rust-version = "1.89.0"
publish = false

[package.metadata."docs.rs"]
rustdoc-args = ["--html-in-header", "arborium-header.html"]

[features]

[dependencies]
benchmark-defs = { path = "../tools/benchmark-defs", version = "0.42.0" }
facet = { path = "../facet", version = "0.43.0", features = ["all-impls", "doc"] }
facet-args = { path = "../facet-args", version = "0.43.0" }
facet-json = { path = "../facet-json", version = "0.42.1" }
flate2 = "1.1"
miette = { workspace = true }
rmpv = "1.3"
serde = { workspace = true }
serde_json = { workspace = true }
ureq = "2.12"
wordfreq = "0.2.3"
zip = "2.4"

[lints]
workspace = true
