[package]
name = "benchmark-defs"
version = "0.42.0"
edition = "2024"
rust-version = "1.89.0"
publish = false

[package.metadata]

[package.metadata."docs.rs"]
rustdoc-args = ["--html-in-header", "arborium-header.html"]

[dependencies]
facet = { path = "../../facet", version = "0.43.0" }
facet-args = { path = "../../facet-args" }
facet-kdl = { path = "../../facet-kdl" }

[lints]
workspace = true
